# Generated by Django 5.1.3 on 2024-11-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_telegramuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='section',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ManyToManyField(to='sections.section'),
        ),
    ]
